### ISSUE TITLE
Sound menu button breaks when NUM_SAVE_FILES is defined to lower values than 4

### ISSUE THREAD

**Issue by splitmare** [AloUltraExt/sm64ex-alo#37]
**Describe the bug**
Setting the definition of the number of save files to less than 4 results in the sound menu text being f***ed up aswell as the button causing a segfault when pressed.
Also the game's console will display:
``NULL texture: tile 0, format 3/0, size 64``

**To Reproduce**
Edit line 12 in ``src/game/save_file.h`` and change ``#define NUM_SAVE_FILES`` to a lower number than 4  

**Expected behavior**
Sound menu button works

**Screenshots**
![image](https://user-images.githubusercontent.com/80412260/222583611-1246786f-00ad-4154-8dd5-0e1e60f739c0.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 64 Bit

**Additional context**
I feel like fixing something like this may be an improvement for anyone wanting an easy way to mod the amount of save files I guess?? It's not very severe anyway and not that necessary but I just thought I'd mention it.

Removing all code related to File C & D does not seem to fix it either. (although I got the game to compile still and run fine.) (see screenshot above)
Setting the value to 0 makes it work again but you cant exit the menu after entering.

### PS: I would like if you can also provide some context why something like this would happen because I can't figure it out.

# havent tested higher values yet....

**Comment by AloXado320** [comment]
Since `NUM_SAVE_FILES `is used on the save file, values gets shifted around when you change them.

In this case `textSoundModes[sSoundMode]` is drawing an invalid string on since `sSoundMode` is greater than 2.

**Comment by AloXado320** [comment]
Fixed on afb7cd0
