### ISSUE TITLE
Crash On Selecting "Display" Option

### ISSUE THREAD

**Issue by Dogeisbest** [AloUltraExt/sm64ex-alo#46]
**Describe the bug**
Going into a brand new/complete save and selecting the "Display" option in the menu will instantly crash the game.

**To Reproduce**
1. Select a save
2. Press your pause button
3. Go into the options menu
4. Go down and click "Display"

**Expected behavior**
I expected to be able to change my resolution, FPS, and other display settings.

**Screenshots**
![image](https://github.com/AloUltraExt/sm64ex-alo/assets/29840719/038ef524-7b90-4302-8d90-a9cce7f572ce)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Most Recent Version

**Additional context**
I have compiled the game entirely through sm64pcBuilder2.
![image](https://github.com/AloUltraExt/sm64ex-alo/assets/29840719/3e9f3860-0e40-4bd7-b29f-16e8a0e452cf)

**Comment by AloXado320** [comment]
![image](https://github.com/AloXado320/sm64ex-alo/assets/38191089/5d44118a-f181-4770-a1be-aacce3c2ae2a)
Works for me, looking at the crash screen, it looks like it tried to get a position of a text that didn't get loaded (on time probably)?

**Comment by Doodl0** [comment]
I am also getting a similar crash, do you have any solution available?
![image](https://github.com/AloUltraExt/sm64ex-alo/assets/52604696/08b10e08-085a-42f7-b4ee-3b472ea85b0b)

**Comment by UnknownSkid** [comment]
i fixed it!! delete the config file in appdata roaming sm64ex or smth like that

**Comment by Doodl0** [comment]
> i fixed it!! delete the config file in appdata roaming sm64ex or smth like that

I'll try this at some point, but good to know

**Comment by AloXado320** [comment]
@UnknownSkid @Doodl0 Just so you guys know, send me your faulty config files, could be due to options loading "garbage" text

**Comment by Doodl0** [comment]
> @UnknownSkid @Doodl0 Just so you guys know, send me your faulty config files, could be due to options loading "garbage" text

Sorry, it's been a while since I last compiled the game and I have since lost my original config. Previously, I compiled for windows, but I just compiled for Linux and the display options all seem to work fine.

**Comment by AloXado320** [comment]
So turns out it's kind of my fault https://github.com/AloUltraExt/sm64ex-alo/issues/71#issuecomment-2495649385

In short, I removed three point from menu because it was broken at times, might need to properly add it while fixing this crash
