### ISSUE TITLE
coins (red and yellow) reset when walking into cabin on cool, cool mountain, wii u 60fps

### ISSUE THREAD

**Issue by grandosegood** [AloUltraExt/sm64ex-alo#54]
**Describe the bug**
when playing wii u 60 fps build, the coins will reset after exiting the cabin at cool cool mountain

**To Reproduce**
earn coins, enter cabin at cool cool mountain, exit,

**Expected behavior**
coun count (yellow and red) stays the same upon entering and exiting the cabin

**Comment by Crockos** [comment]
This happen on Switch too, I don't think it's a 60fps related or platform bug I mean the project has "frame interpolation" so it does not break any behavior or physics of the game but yeah the bug exists till this day.

**Comment by AloXado320** [comment]
Seems to be a problem with macro objects after I removed it's bparam3 requirement from 231034ed2f49a679ab0bc3743708777a62ce9d2d. The repo i took the implementation from had macro objects removed, that's why I didn't caught it.

**Comment by AloXado320** [comment]
Fixed on afb7cd0
