### ISSUE TITLE
Can't run on Android

### ISSUE THREAD

**Issue by Dv5n** [AloUltraExt/sm64ex-alo#61]
**Describe the bug**
Compiled successfully on Termux (on another device)
but after I installed the APK, it says "SDL Error" (This happens on multiple sm64 android ports (except for sm64ex-coop) on both of the devices)

**To Reproduce**
1. Compile.
2. Install APK.
3. See error.

**Expected behavior**
To work.

**Screenshots**
![Screenshot_2024-06-13-15-23-20-696_com.vdavid003.sm64port.jpg](https://github.com/AloUltraExt/sm64ex-alo/assets/118058649/5301a335-af27-457e-8b0a-37ddd6da7e20)

**Desktop:**
 - OS: Android 14 (Compiled on Android 11 but still errors)

**Smartphone:**
 - Device: Redmi note 12 (Compiled on Samsung Galaxy a20e)

**Additional context**
Most newest packages.
:-(

**Comment by Algiuxs** [comment]
Had the exact issue, solved it by running
"
 pkg remove libglvnd
"
Then retrying to build the project

**Comment by Algiuxs** [comment]
> Had the exact issue, solved it by running
> 
> >  pkg remove libglvnd
> 
> Then retrying to build the project
If you have installed the libglvnd, then remove it, because it causes libraries to be included, that shouldn't.

**Comment by Dv5n** [comment]
But it removes other packages that I installed (ex: xfce)

**Comment by Algiuxs** [comment]
> But it removes other packages that I installed (ex: xfce)

It's the only way to resolve the issue, at least I believe.
I know it's annoying, but you can write down what packages are deleted, and install them after the compilation is done.

**Comment by Dv5n** [comment]
Compiled and works. Thanks.

**Comment by AloXado320** [comment]
Fixed on f3cd1a16197ecf8d7cb6711e7e81bf89ff05f291, tested on my Poco X3 Pro with a custom rom using Android 14
