### ISSUE TITLE
Switch Build Broken

### ISSUE THREAD

**Issue by impeeza** [AloUltraExt/sm64ex-alo#62]
**Describe the bug**
I am able to build PC version without flaws:

I am using MSYS's MINGW64, installing the packages:

`pacman -Syuu --needed --noconfirm base-devel git make mercurial python3 subversion unzip autoconf automake libtool pkg-config autoconf-wrapper mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc mingw-w64-x86_64-glew mingw-w64-x86_64-SDL2 mingw-w64-x86_64-toolchain mingw-w64-x86_64-SDL switch-dev devkitA64 dkp-toolchain-vars libnx switch-tools switch-mesa switch-libdrm_nouveau switch-sdl2`

Cloning the repo:

`git clone --recursive https://github.com/AloUltraExt/sm64ex-alo`

Copied my original ROM to the root of repo

and run the command:
`make BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1`

But trying to build the Switch, using the command:

`make TARGET_SWITCH=1 BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1`

I got the errors:

![image](https://github.com/AloUltraExt/sm64ex-alo/assets/41979604/0d2c5864-9025-4102-ba84-bf1f1e1f8c34)

it's supposed you need include switch.h to avoid that error but including it generate a lot of new errors.

**Comment by impeeza** [comment]
The switch version is still broken,  any hope switch version can be build again?  thanks.

**Comment by impeeza** [comment]
@AloXado320 Greetings from Colombia, sorry for bother,  have you had time to look in to this?

Regards.

**Comment by jnackmclain** [comment]
I just got a build working and made a pr @impeeza 
#67

**Comment by impeeza** [comment]
Excellent!  worked like a charm:


![image](https://github.com/user-attachments/assets/542f0fd9-2003-4a2d-b10f-74a9f5563211)


so with PR 67 merge this issue will be closed

**Comment by AloXado320** [comment]
Thanks for the PR! Merged c1ea363
