### ISSUE TITLE
OSError: [Errno 8] Exec format error: './tools/skyconv'

### ISSUE THREAD

**Issue by yamathedestroyer** [AloUltraExt/sm64ex-alo#65]
I guess this is obsolete now, redownloading the repo fixed is so somehow building that failed the first time idk. 

Build Now fails at
src/pc/pc_main.c: In function 'main_func':
src/pc/pc_main.c:419:12: error: implicit declaration of function 'appletMainLoop' [-Wimplicit-function-declaration]
  419 |     while (appletMainLoop())
      |            ^~~~~~~~~~~~~~
make: *** [Makefile:1641: build/us_nx/src/pc/pc_main.o] Fehler 1

Help would very much be appreciated

////////////////////////////////
When trying to make, it fails with an Exec Format Error for /tools/skyconv, my machine is x86-64 and im building on arch linux. Executing the binary directly also fails with "zsh: exec format error: ./tools/skyconv"

The full Error is

extracting levels/ending/cake.png
cake /tmp/assetxqboh5va levels/ending/cake.png
Traceback (most recent call last):
  File "/home/yama/sm64ex-alo/extract_assets.py", line 313, in <module>
    main() if __name__ == "__main__" else None
    ^^^^^^
  File "/home/yama/sm64ex-alo/extract_assets.py", line 255, in main
    subprocess.run(
  File "/usr/lib/python3.12/subprocess.py", line 549, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1027, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1956, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './tools/skyconv'
Makefile:437: *** Failed to extract assets from US ROM.  Schluss.

**Comment by TCAtrevor** [comment]
I am having this issue with skyconv right now. Redownloading it is not fixing it for me.

**Comment by qwertyad1** [comment]
bruh im having this issue rn
