### ISSUE TITLE
Crash on display option

### ISSUE THREAD

**Issue by UnknownSkid** [AloUltraExt/sm64ex-alo#71]
**Describe the bug**
Game Crashes when i select display in options, theyre trying to hide something from me

**To Reproduce**
1. Go to Display in options
2. Crash ):

**Expected behavior**
i expected to be able to change the fps limit my resolution and if i want to play with 4:3 ratio and stuff like that

**Screenshots**
![image](https://github.com/user-attachments/assets/c93f31a3-62f0-48c9-95f0-70ded891925a)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Bowser: Google Chrome
 - Version: idk

**Additional context**
No

**Comment by UnknownSkid** [comment]
> Duplicate of #46, it's a strange issue I couldn't replicate on my end...

darn

**Comment by AloXado320** [comment]
@UnknownSkid Does it happen whenever you create a new or use an existing save file?

**Comment by UnknownSkid** [comment]
I FIXED IT, i deleted the uhh config file whatever and now i can go into display, thought there would be more settings tho

**Comment by UnknownSkid** [comment]
I FIXED IT, i deleted the uhh config file whatever and now i can go into display, thought there would be more settings tho

**Comment by Flower35** [comment]
Hi. The problem must have been the `texture_filtering` option in `"sm64config.txt"`.

The `"sm64ex"` repo defines 3 options for `filterChoices[]` in `"src/game/options_menu.c"`
- [0] => optsVideoStr[2] => TEXT_OPT_NEAREST => "NEAREST"
- [1] => optsVideoStr[3] => TEXT_OPT_LINEAR => "LINEAR"
- [2] => optsVideoStr[8] => TEXT_OPT_THREEPT => "THREE POINT"

https://github.com/sm64pc/sm64ex/blob/57c203465b2b3eee03dcb796ed1fad07d8283a2c/src/game/options_menu.c#L127-L131

However, the third option was removed in the "Remove Three-point toggle from options menu" commit:

https://github.com/AloUltraExt/sm64ex-alo/commit/e1ec0d2aa40d2f96cef034cf15cce17ffec6a73e#diff-78160a0a0fb15b76351a29ea1a1f0aa6dd5269e34e9f9300ee1315f92dd741cdL137

And so, if `texture_filtering` is set to `2`, `unsigned int configFiltering` will be loaded with that value, not checking if it is a valid index, and it will reference out-of-bounds static data, which ends up being a bunch of zeroes, so a NULL pointer to an invalid string.

By deleting `"sm64config.txt"` or replacing `texture_filtering` with values in range `[0, 1]`, the problem no longer occurs.

**Comment by UnknownSkid** [comment]
> Hi. The problem must have been the `texture_filtering` option in `"sm64config.txt"`.
> 
> The `"sm64ex"` repo defines 3 options for `filterChoices[]` in `"src/game/options_menu.c"`
> 
> * [0] => optsVideoStr[2] => TEXT_OPT_NEAREST => "NEAREST"
> * [1] => optsVideoStr[3] => TEXT_OPT_LINEAR => "LINEAR"
> * [2] => optsVideoStr[8] => TEXT_OPT_THREEPT => "THREE POINT"
> 
> https://github.com/sm64pc/sm64ex/blob/57c203465b2b3eee03dcb796ed1fad07d8283a2c/src/game/options_menu.c#L127-L131
> 
> However, the third option was removed in the "Remove Three-point toggle from options menu" commit:
> 
> [e1ec0d2#diff-78160a0a0fb15b76351a29ea1a1f0aa6dd5269e34e9f9300ee1315f92dd741cdL137](https://github.com/AloUltraExt/sm64ex-alo/commit/e1ec0d2aa40d2f96cef034cf15cce17ffec6a73e#diff-78160a0a0fb15b76351a29ea1a1f0aa6dd5269e34e9f9300ee1315f92dd741cdL137)
> 
> And so, if `texture_filtering` is set to `2`, `unsigned int configFiltering` will be loaded with that value, not checking if it is a valid index, and it will reference out-of-bounds static data, which ends up being a bunch of zeroes, so a NULL pointer to an invalid string.
> 
> By deleting `"sm64config.txt"` or replacing `texture_filtering` with values in range `[0, 1]`, the problem no longer occurs.

Fajnie
