### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by catfromplan9** [AloUltraExt/sm64ex-alo#73]
**Describe the bug**

Game freezes in big boo level for the red coins star, when i get the star it just goes to a black screen instead of kicking me back to the hub world. I'm on the switch ver with these make flags 

`make TARGET_SWITCH=1 BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1 HIGH_FPS_PC=1`

I got the star for killing all the boos prior to this but didnt collect it, not sure if that caused it, but prior to updating (i was previously using the branch that fixed switch support) i also got this freeze in flying cap star for bombomb battlefield, it was resolved when i updated. Same black screen freeze. No buttons respond to input.

**Comment by catfromplan9** [comment]
Can confirm it only happens when i got two stars, but it always happened in bombomb battlefield. Im not sure if anything even fixed it in the update i did?

**Comment by AloXado320** [comment]
Are you using the latest commit? You say there's a crash on both BOB and BBH, is that correct?

**Comment by catfromplan9** [comment]
> Are you using the latest commit? You say there's a crash on both BOB and BBH, is that correct?

Yes latest commit as of today, and it doesnt crash consistently, BBH worked when I only got the one red coin star. Heres what i did maybe you can replecate it: enter big boos haunt and get first star (for killing the boos and fighting the big boo) then get the red coin star too without redeeming the first star and grab the red coin star

**Comment by AloXado320** [comment]
I added more sanity checks after the fork so I assume BOB was fixed with that but there's still something being read as nan in BBH (collision? camera? not sure) or something, save files could help though.

I'm also suspecting about `NODRAWINGDISTANCE=1`, does the crashes still happen with that disabled?

**Comment by catfromplan9** [comment]
> I added more sanity checks after the fork so I assume BOB was fixed with that but there's still something being read as nan in BBH (collision? camera? not sure) or something, save files could help though.
> 
> I'm also suspecting about `NODRAWINGDISTANCE=1`, does the crashes still happen with that disabled?

I will test later, but what does this do?

**Comment by catfromplan9** [comment]
You can test yourself if you want, id prefer that, i can link you my save file and the repo to build with if you have a switch

**Comment by catfromplan9** [comment]
I rebuilt, used my old save, and redid the BOB star. It doesnt occur now for some reason...

**Comment by AloXado320** [comment]
> You can test yourself if you want, id prefer that, i can link you my save file and the repo to build with if you have a switch (for BOB)

I do have one, send the save if you can.

> I rebuilt the older build, used my old save, and redid the BOB star. It doesnt occur now for some reason...

Again, there could be something not being properly read sometimes, if a save can show some consistent result I could fix it.

**Comment by catfromplan9** [comment]
I just did BBH and got the merry go round star, then the red coins star, it happened. Seems to happen if you get two stars in BBH. Will now try in BOB as well to test if this is always the case.

**Comment by catfromplan9** [comment]
Just tried the mario wings to the sky star in BOB while unlocking shoot to the island in the sky star too but nor collecting it. Didn't happen that time. I will try BBH one again now.

**Comment by catfromplan9** [comment]
Okay now i cant replecate. Im going to try this again, and i will record it for you

**Comment by catfromplan9** [comment]
Cant replicate it :( ugh, I'm even using the same save. It happens fairly regularly to me, try just playing through the game collecting sometimes multiple stars and it will happen eventually im pretty sure

**Comment by catfromplan9** [comment]
Skipped 50 and 70 star doors with BLJ, I got a black screen when entering the boss level twice in a row. I will turn off NODRAWINGDISTANCE and play through the game, and I'll let you know if it ever happens again.

**Comment by catfromplan9** [comment]
A trend I've noticed is, it is more likely to happen if I have been playing for longer, even if I have not entered into levels. Maybe I'm just trying to draw conclusions though, it's hard for me to say

**Comment by catfromplan9** [comment]
Got a crash with `NODRAWINGDISTANCE=1` not being set in my build, while jumping into the wet dry world portal after running around for a bit  (~30 minutes BLJing up stairs and stuff)

![image](https://github.com/user-attachments/assets/e18e1db9-aac9-4ec8-8694-7be85e604a9b)

**Comment by catfromplan9** [comment]
Launched into wet dry world, AFKed for over an hour doing nothing, then exiting the level from options menu I also get a black screen. @AloXado320 you should be able to reproduce this

**Comment by catfromplan9** [comment]
To be clear, this ^ is not related to WDW. It relates to any level. Go into a level (even the hub world), wait for an hour, and try to leave the level, see what happens

**Comment by catfromplan9** [comment]
@AloXado320 can you please look into this?? The game is borderline unplayable on switch, every time I enter a level to get a star I'm gambling on if it'll crash when I leave or not

**Comment by AloXado320** [comment]
@catfromplan9 I'm suspecting one of the QOL_FEATURES is causing problems, can you disable it using `QOL_FEATURES=0`?

**Comment by catfromplan9** [comment]
> @catfromplan9 I'm suspecting one of the QOL_FEATURES is causing problems, can you disable it using `QOL_FEATURES=0`?

That is already off

**Comment by catfromplan9** [comment]
I'm testing it now. Another issue: in WDW, with `QOL_FEATURES=0`, the raft(?) platforms in the water are not solid, I can swim right through them and fall through them

**Comment by catfromplan9** [comment]
@AloXado320 With `QOL_FEATURES=0`, the crash still happens.

**Comment by AloXado320** [comment]
I accidentally replicated what I could be the same issue in less time.

* I entered debug level select during title screen (L+R+Start)
* Waited maybe 10-20 minutes
* Selected Wet Dry World
* Screen hangs at white screen with no response from the window

It didn't seem to crash (otherwise the crash handler would be shown), so it seems to hang somewhere...

**Comment by AloXado320** [comment]
Got it, I should have suspected back then, there's a block of code in `audio_reset_session` here that is only set in JP and US:
```c
        while (remainingDmas > 0) {
            for (i = 0; i < gCurrAudioFrameDmaCount; i++) {
                if (osRecvMesg(&gCurrAudioFrameDmaQueue, NULL, OS_MESG_NOBLOCK) == 0)
                    remainingDmas--;
            }
        }
```
Incidentally `osRecvMesg` is a stub only in JP and US, so if there's `remainingDmas` values, it never decreases and game gets stuck after audio has played long enough. Since this block is only used on the versions previously mentioned, the ideal solution would be removing the block of code like in EU (HackerSM64 has this done as well). I'll need further test to ensure audio still works.

**Comment by catfromplan9** [comment]
> Got it, I should have suspected back then, there's a block of code in `audio_reset_session` here that is only set in JP and US:
> 
> ```c
>         while (remainingDmas > 0) {
>             for (i = 0; i < gCurrAudioFrameDmaCount; i++) {
>                 if (osRecvMesg(&gCurrAudioFrameDmaQueue, NULL, OS_MESG_NOBLOCK) == 0)
>                     remainingDmas--;
>             }
>         }
> ```
> 
> Incidentally `osRecvMesg` is a stub only in JP and US, so if there's `remainingDmas` values, it never decreases and game gets stuck after audio has played long enough. Since this block is only used on the versions previously mentioned, the ideal solution would be removing the block of code like in EU (HackerSM64 has this done as well). I'll need further test to ensure audio still works.

Great to hear, thank you

**Comment by AloXado320** [comment]
@catfromplan9 Try now, and I also fixed platforms with `QOL_FEATURES=0`. Let me know if the freeze is gone.

**Comment by catfromplan9** [comment]
> @catfromplan9 Try now, and I also fixed platforms with `QOL_FEATURES=0`. Let me know if the freeze is gone.

Thank you, will do

**Comment by catfromplan9** [comment]
https://github.com/AloUltraExt/sm64ex-alo/commit/7f01d556a74828d83a9d58e829b946e8bb9eaa38 fixes it, correct?

**Comment by catfromplan9** [comment]
Can confirm it is fixed, thank you
